name: Build and Test

on:
  push:
  schedule: 
    - cron: '0 0 * * *'    

jobs:

  # dotnet components
  dotnet:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib

    steps:
    - uses: actions/checkout@v2
    - name: Restore Packages
      run: dotnet restore
    - name: Build Core
      run: dotnet build Whalerator
    - name: Build WebAPI
      run: dotnet build Whalerator.WebAPI
    - name: Run Tests
      run: dotnet test Whalerator.Test

  # node/angular components
  angular:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm install
    - name: Build SPA
      run: npm run build
    - name: Run Tests
      run: npm run test-headless
